health:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: itcast_health
    username: root
    password: 654321
  #阿里云oss配置
  alioss:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    access-key-id: LTAI5t69jEzoLn8avUBodKTp
    access-key-secret: wb5fkPd3JNAdK5uPgKnAWJbS241krD
    bucket-name: web-25
  # redis配置
  redis:
    host: localhost
    port: 6379
    #    password: 123456
    database: 10
#spring:
#  freemarker:
#    template-loader-path: classpath:/templates/
#    suffix: ftl
#freemarker:
#  out:
#    path: D:\work\沉浸式项目实战\bxg-health-parent\bxg-health-mobile\src\main\resources\mobile\pages